sonar.projectKey=alexdarenkov_messanger-alti
sonar.organization=alexdarenkov
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info